"""empty message

Revision ID: ed9a404fcc79
Revises: 3ccf222b169f
Create Date: 2021-03-21 04:36:02.048302

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ed9a404fcc79'
down_revision = '3ccf222b169f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_tags',
    sa.Column('binary_network_part', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('binary_network_part')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.drop_table('network_tags')
    # ### end Alembic commands ###
